version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hospital-system-app
    container_name: hospital-app
    restart: unless-stopped
    ports:
      - "8000:8000" # Map to Laravel's Artisan serve port
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your_app_key_here # Generate with php artisan key:generate
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hospital_system
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - GROQ_API_KEY=your_groq_api_key_here
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: hospital-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hospital_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hospital-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata: